# Generated by Django 4.1.3 on 2022-12-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_mensaje_delete_mensajes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(max_length=5000),
        ),
    ]
