# Generated by Django 4.1.3 on 2022-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_about_marca_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, unique=True)),
                ('subtitulo', models.CharField(max_length=50, unique=True)),
                ('cuerpo', models.CharField(max_length=100)),
                ('autor', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
