# Generated by Django 4.1.3 on 2022-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=25)),
            ],
        ),
    ]
