# Generated by Django 4.1.3 on 2023-01-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0007_perfil_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
